version: '3.7'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8888:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mariadb
    networks:
      - laravel
  mariadb:
    image: mariadb:10.2
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Gascontrol2022*laravel-web
      MYSQL_DATABASE: gascontrol
      MYSQL_USER: root
      MYSQL_PASSWORD: Gascontrol2022*laravel-web
    ports:
      - 33069:3306
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - laravel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: Gascontrol2022*laravel-web
    depends_on:
      - mariadb
    networks:
      - laravel
  php:
    image: php:7.4.7
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
    networks:
      - laravel
  nodejs:
    image: node:12.14
    container_name: nodejs
    ports:
      - 3000:3000
    working_dir: /var/www/html/gascontrol
    volumes:
      - ./src/gascontrol:/var/www
    networks:
      - laravel
networks:
  laravel:
    