name: Laravel

on:
  push:
    branches: [ feature/github-actions-implementation ]
  #pull_request:
  #  branches: [ develop ]

jobs:
  laravel-tests:
    # local run
    runs-on: self-hosted

    # service run
    #runs-on: ubuntu-latest

    steps:
    # In WINDOWS with self-hosted we doesn't need actions for php
    # - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
    #  with:
    #    php-version: '8.1.2'

    # Checkout to branch in the repository
    - uses: actions/checkout@v3

    # ENV
    # In WINDOWS: we need set permissions for self-hosted
    # Get-ExecutionPolicy -List ​
    # Set-ExecutionPolicy RemoteSigned -Scope CurrentUser ​
    - name: Copy .env
      run: |
        cd src/gascontrol/
        php -r "file_exists('.env') || copy('.env.example', '.env');"
    
    # Composer dependencies
    - name: Install Dependencies
      run: |
        cd src/gascontrol/
        composer install
    # KEY
    - name: Generate key
      run: |
        cd src/gascontrol/
        php artisan key:generate

    # Run Migrations
    - name: Run Migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: b9mrufjbdcpd0unu05nw-mysql.services.clever-cloud.com
        DB_DATABASE: b9mrufjbdcpd0unu05nw
        DB_USERNAME: u0h75mwxovo7bd7n
        DB_PASSWORD: dhXKCgAak1BSZWQGZQF2
      run: |
        cd src/gascontrol/
        php artisan migrate

    # Unit Test and Feature Test
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_HOST: b9mrufjbdcpd0unu05nw-mysql.services.clever-cloud.com
        DB_DATABASE: b9mrufjbdcpd0unu05nw
        DB_USERNAME: u0h75mwxovo7bd7n
        DB_PASSWORD: dhXKCgAak1BSZWQGZQF2
      run: |
        cd src/gascontrol/
        vendor/bin/phpunit

    # Directory permissions for linux or mac:
    #- name: Directory Permissions
    #  run: |
    #   cd src/gascontrol/
    #   chmod -R 777 storage bootstrap/cache
    
